### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by drejc12** [bzgec/python_helperLib#1]
I have found a big bug in your code, when sending an email with attachment. To recreate my issue, follow my code:

```
import mailSender

mailSenderHandle = mailSender.Mail('a***gmail.com', 'n**b')

mailSenderHandle.send('b***@gmail.com', 'Test', 'Test1', ['test.txt'])
```

Response:
```
with open(file_path, "rb") as file:
FileNotFoundError: [Errno 2] No such file or directory: 't'
```

Running Windows 10 Pro 64-bit
Version: 10.0.19043 Build 19043
Processor: Procesor	11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz, 2803 MHz
RAM: 16 GB

**Comment by bzgec** [comment]
If I understand correctly this works:

> import mailSender
> 
> mailSenderHandle = mailSender.Mail('a***gmail.com', 'n**b')
> 
> mailSenderHandle.send('b***@gmail.com', 'Test', 'Test1', ['test.txt'])

But this doesn't:
`mailSenderHandle.send('b***@gmail.com', 'Test', 'Test1', 'test.txt')`

I have implemented a [fix](https://github.com/bzgec/python_helperLib/tree/fix/mailSender/sendAcceptsOnlyList) which allows the `send` function to accept a single file as well as a list/array.

**Comment by drejc12** [comment]
This is working now. I was missing the list in the attachments parameter.
