### ISSUE TITLE
Multiple mail addresses receivers

### ISSUE THREAD

**Issue by drejc12** [bzgec/python_helperLib#3]
Please include a option to send a mail to multiple addresses at the sime time.
Maybe a list with only one or more receivers would be best way to implement it.

**Comment by bzgec** [comment]
I have implemented a [fix](https://github.com/bzgec/python_helperLib/tree/fix/mailSender%2FmultipleRecipients).

You can use it the same way as for the attachments:
```
import helperLib.mailSender as mailSender

mailSenderHandle = mailSender.Mail('sender@gmail.com', 'senderPassword')

mailSenderHandle.send('receiver1@gmail.com', 'Test - 1', 'Single receiver')
mailSenderHandle.send(['receiver1@gmail.com', 'receiver2@gmail.com'], 'Test - 2', 'Multiple receivers')
```

Note that you can also use it directly from terminal:
```
python mailSender.py -f sender@gmail.com -p senderPassword -r receiver1@gmail.com -x 'Test - 1' -c 'Single receiver' 
python mailSender.py -f sender@gmail.com -p senderPassword -r receiver1@gmail.com -x 'Test - 2' -c 'Multiple receivers' -r receiver2@gmail.com
```

**Comment by bzgec** [comment]
Is it working on your side?

**Comment by drejc12** [comment]
It works now, thanks!
